version: "3.1"

services:
  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
