version: "3.1"

services:
  nginx:
    image: bitnami/openresty:latest
    ports:
      - "80:80"
      - "81:81"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/opt/bitnami/openresty/nginx/conf/server_blocks/my_server_block.conf:ro
