version: "3.1"

volumes:
  local-mongo:

services:
  mongo:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      # - local-mongo:/data/db
      - ./:/backup
    # xz -dc stubber_mongodb_backup.xz | mongorestore -vv --uri="mongodb://admin:admin@localhost:27017" --authenticationDatabase=admin --nsInclude="admin.*" --archive

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
