services:
  monstache:
    image: rwynn/monstache:6.7.2
    container_name: monstache
    working_dir: /app
    command: -f ./monstache.config.toml
    volumes:
      - ./monstache.config.toml:/app/monstache.config.toml
    depends_on:
      mongo:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: "wget -q -O - http://localhost:8080/healthz"
      interval: 10s
      timeout: 30s
      retries: 300
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    logging:
      driver: none
    container_name: mongo
    command: /scripts/mongo-run.sh
    working_dir: /scripts
    volumes:
      - ./mongodb/scripts:/scripts
      - mongodb-stubber-dev:/data/db
    environment:
      MONGO_REPLICA_SET_NAME: rs0
      MONGO_REPLICAS: mongo:27017
      MONGO_REPLICA_SET_MEMBERS: "[{'_id':0,'host':'mongo:27017','priority':1}]"
      MONGO_USER_ROOT_NAME: root
      MONGO_USER_ROOT_PASSWORD: wortel
      MONGO_AUTH_SOURCE: admin
      MONGO_BIND_IP: "0.0.0.0"
    ports:
      - "27017:27017"
    healthcheck:
      test: "[ -f /data/health.check ] && exit 0 || exit 1"
      interval: 2s
      timeout: 30s
      retries: 300
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: wortel
      ME_CONFIG_MONGODB_URL: mongodb://root:wortel@mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # -Xms6g -Xmx6g
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    healthcheck:
      test: "curl --fail http://localhost:9200 || exit 1"
      interval: 1s
      timeout: 30s
      retries: 300
    restart: unless-stopped

volumes:
  esdata1:
  mongodb-stubber-dev:
